#!/usr/bin/python

dna="CTGGCCTGGAGCAAGTCTTAGGTACAGCCGTAATGAGCTCGAATGGCGTCGCACTTTACGCCTGGTCAACACGCCATTAGCTCCCGGCCAACACGTATCATGCAAATCATCCTATGAGAATTCACCGTACTGGTTGGAATTGTGGCACAGTCATAGATTTAACATATTATACAATAAGCATACCAGGGTCCCAGCGTCTGTTGTTTTCCGTCCCCTCTCAATATAAGGGCACTGGGATTATCTTAAAACCGGGCAAATCAAGACAACGACGCACCATGGTGTCTACCAATCGTTGATACAGTGGAGATTGAGGCTAGAAGCGTGTCTTTCTTGAAAGTTCCTCGACGTCCAGTGAACGGCACAGAGTAACCCGTTGGCCGTATGCCGGTTCGCGCGGTGTCCTTTGTACGCGTGACCAATACCATCTTCTGTCTGGGAAGATCCCCGCCTTCGCCGACTATGCAAGTCCATAAATCCGTAATCACGTCTTTAATGGCGCTCCGCGTTTCCAATCTCGAGGTCATTAGGCTTTCTCAAGTCAATAGGTTTTCGGTGTCGGCGACTCTCTATTTGAGAGGATTGGGCGGGGTGGGGGTCCCAAAGGATATCACACCGATAGCGGACGGGGAATACCTCTTTGCCGTATAGTATCCCGACCACAGGGCCGGATCCTCGTGTGCGCTCTGCAGGCGCGAGATTCACTCGGTACAGGAAAAGGGAATCCCTTTGGCCCTATAAACTAGTTAAGGACCCCTAGAGTGAAGAACTACAACGTATGGATTTAGGTCTGCTTCATGTTGGAACTGGACGCATTA"
string = ""
for letter in dna:
    if letter == 'A':
        string = string + 'T'
    elif letter == 'T':
        string = string + 'A'
    elif letter == 'G':
        string = string + 'C'
    else:
        string = string + 'G'

print string[::-1]
